[package]
name = "MEME"
version = "0.0.0"

[addresses]
MEME = "input your address"
admin_account="input your address"


[dependencies]
AptosFramework = { local = "../aptos-core/aptos-move/framework/aptos-framework" }
